FROM php:8.3.7-apache

# ドキュメントルートを変更
ENV APACHE_DOCUMENT_ROOT /var/www/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# パッケージインストール
RUN apt-get update && apt-get install -y \
    libicu-dev \
    libonig-dev \
    libzip-dev \
    zlib1g-dev \
    unzip \
    locales \
    vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Apache の rewrite_module を有効化
RUN a2enmod rewrite

# PHP のエクステンションをインストール
RUN docker-php-ext-install \
    intl \
    pdo_mysql \
    zip

RUN pecl install xdebug && \
    docker-php-ext-enable xdebug

# ---- 追加設定（警告対応） ----
# intl の二重読み込み防止（これで完全に警告消える）
RUN rm -f /usr/local/etc/php/conf.d/docker-php-ext-intl.ini

# タイムゾーン設定
RUN echo "date.timezone = Asia/Tokyo" > /usr/local/etc/php/conf.d/timezone.ini

# Xdebug 無効化（ログ関連警告回避）
RUN echo "xdebug.mode=off" > /usr/local/etc/php/conf.d/disable-xdebug.ini
# ---- ここまで ----

# Composer インストール
COPY --from=composer /usr/bin/composer /usr/bin/composer

# コンテナログイン時のパス指定
WORKDIR /var/www
