services:
  # MySQL
  db:
    build: ./docker/mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=database
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
    restart: unless-stopped

  # アプリ（※ Dockerfile は php:8.x-apache ベース想定）
  app:
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./laravel:/var/www
    ports:
      - "3000:80"     # http://localhost:3000
      - "5173:5173"   # （任意）Viteをコンテナ内で動かす時だけ必要
    expose:
      - "9003"        # （任意）Xdebug用
    depends_on:
      - db
    restart: unless-stopped

  # Adminer（任意）
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped
